# Generated by Django 4.2.27 on 2025-12-12 22:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, max_length=10)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "categories",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Rant",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("body", models.TextField()),
                ("is_anonymous", models.BooleanField(default=True)),
                ("display_name", models.CharField(blank=True, max_length=100)),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Optional, for notifications if featured",
                        max_length=254,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_approved", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_reported", models.BooleanField(default=False)),
                ("report_count", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rants",
                        to="rants.category",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SideBySide",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "linkedin_version",
                    models.TextField(help_text="The LinkedIn version (cringe)"),
                ),
                (
                    "reality_version",
                    models.TextField(help_text="The reality (what actually happened)"),
                ),
                (
                    "context",
                    models.CharField(
                        blank=True, help_text="Brief setup/context", max_length=200
                    ),
                ),
                ("is_anonymous", models.BooleanField(default=True)),
                ("display_name", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_approved", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_reported", models.BooleanField(default=False)),
                ("report_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Side by Side",
                "verbose_name_plural": "Side by Sides",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[
                            ("drink", "🍷"),
                            ("dead", "💀"),
                            ("felt", "🤝"),
                            ("rage", "😤"),
                            ("peak", "🎭"),
                            ("clap", "👏"),
                        ],
                        max_length=20,
                    ),
                ),
                ("session_key", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="rants.rant",
                    ),
                ),
                (
                    "sidebyside",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reactions",
                        to="rants.sidebyside",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                fields=("rant", "session_key", "reaction_type"),
                name="unique_rant_reaction",
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                fields=("sidebyside", "session_key", "reaction_type"),
                name="unique_sidebyside_reaction",
            ),
        ),
    ]
