# Generated by Django 4.2.27 on 2025-12-12 22:36

from django.db import migrations


def create_categories(apps, schema_editor):
    Category = apps.get_model('rants', 'Category')
    categories = [
        {
            'name': 'What I Actually Wanted to Post',
            'slug': 'actually-wanted',
            'description': 'The real version of a LinkedIn post',
            'icon': '💭',
            'order': 1,
        },
        {
            'name': 'LinkedIn Deleted This',
            'slug': 'linkedin-deleted',
            'description': 'Content that was removed/censored by LinkedIn',
            'icon': '🚫',
            'order': 2,
        },
        {
            'name': 'Recruiter Horror Stories',
            'slug': 'recruiter-horror',
            'description': 'Bad recruiting experiences',
            'icon': '👻',
            'order': 3,
        },
        {
            'name': 'The Job Search is Broken',
            'slug': 'job-search-broken',
            'description': 'Frustrations with the hiring process',
            'icon': '🔥',
            'order': 4,
        },
        {
            'name': 'Corporate Cringe',
            'slug': 'corporate-cringe',
            'description': 'Absurd workplace culture moments',
            'icon': '😬',
            'order': 5,
        },
        {
            'name': 'LinkedIn Lunacy',
            'slug': 'linkedin-lunacy',
            'description': 'Mocking specific LinkedIn tropes',
            'icon': '🤪',
            'order': 6,
        },
        {
            'name': 'General Rant',
            'slug': 'general',
            'description': 'Anything else career/work related',
            'icon': '📢',
            'order': 7,
        },
    ]
    for cat_data in categories:
        Category.objects.create(**cat_data)


def remove_categories(apps, schema_editor):
    Category = apps.get_model('rants', 'Category')
    Category.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("rants", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(create_categories, remove_categories),
    ]
