# Generated by Django 4.2.27 on 2025-12-16 01:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("rants", "0002_populate_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="GhostingStory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "recruiter_name",
                    models.CharField(
                        blank=True,
                        help_text="Recruiter's name (optional)",
                        max_length=200,
                    ),
                ),
                ("company", models.CharField(max_length=200)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("indeed", "Indeed"),
                            ("other", "Other"),
                        ],
                        default="linkedin",
                        max_length=20,
                    ),
                ),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("applied", "Just Applied"),
                            ("screening", "Phone Screen"),
                            ("interview", "After Interview(s)"),
                            ("final", "Final Round"),
                            ("offer", "Verbal Offer Stage"),
                            ("other", "Other"),
                        ],
                        default="applied",
                        max_length=20,
                    ),
                ),
                (
                    "story",
                    models.TextField(
                        help_text="What happened? How did they ghost you?"
                    ),
                ),
                ("is_anonymous", models.BooleanField(default=True)),
                ("display_name", models.CharField(blank=True, max_length=100)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_approved", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_reported", models.BooleanField(default=False)),
                ("report_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Ghosting Story",
                "verbose_name_plural": "Ghosting Stories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="reaction",
            name="ghosting_story",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reactions",
                to="rants.ghostingstory",
            ),
        ),
        migrations.AddConstraint(
            model_name="reaction",
            constraint=models.UniqueConstraint(
                fields=("ghosting_story", "session_key", "reaction_type"),
                name="unique_ghosting_reaction",
            ),
        ),
    ]
