# Generated by Django 4.2.27 on 2025-12-16
# Manual migration for LinkedIn share flow feature

from django.db import migrations, models
import django.db.models.deletion
import secrets
import rants.models


def generate_share_slugs(apps, schema_editor):
    """Generate unique share slugs for existing rants and sidebysides."""
    Rant = apps.get_model('rants', 'Rant')
    SideBySide = apps.get_model('rants', 'SideBySide')

    for rant in Rant.objects.all():
        rant.share_slug = secrets.token_urlsafe(6)[:8]
        rant.save(update_fields=['share_slug'])

    for sbs in SideBySide.objects.all():
        sbs.share_slug = secrets.token_urlsafe(6)[:8]
        sbs.save(update_fields=['share_slug'])


def reverse_share_slugs(apps, schema_editor):
    """Reverse migration - nothing to do as fields will be removed."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("rants", "0003_wall_of_shame"),
    ]

    operations = [
        # Step 1: Add share_slug to Rant (nullable, non-unique)
        migrations.AddField(
            model_name="rant",
            name="share_slug",
            field=models.SlugField(max_length=12, null=True, blank=True),
        ),
        # Step 2: Add share_slug to SideBySide (nullable, non-unique)
        migrations.AddField(
            model_name="sidebyside",
            name="share_slug",
            field=models.SlugField(max_length=12, null=True, blank=True),
        ),
        # Step 3: Add linkedin_version to Rant
        migrations.AddField(
            model_name="rant",
            name="linkedin_version",
            field=models.TextField(blank=True, help_text="Optional: The LinkedIn version for sharing"),
        ),
        # Step 4: Create ContentView model
        migrations.CreateModel(
            name="ContentView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "referrer",
                    models.CharField(
                        choices=[
                            ("li", "LinkedIn"),
                            ("tw", "Twitter/X"),
                            ("fb", "Facebook"),
                            ("direct", "Direct"),
                            ("other", "Other"),
                        ],
                        default="direct",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "ghosting_story",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_views",
                        to="rants.ghostingstory",
                    ),
                ),
                (
                    "rant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_views",
                        to="rants.rant",
                    ),
                ),
                (
                    "sidebyside",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="content_views",
                        to="rants.sidebyside",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        # Step 5: Populate share_slug for existing records
        migrations.RunPython(generate_share_slugs, reverse_share_slugs),
        # Step 6: Alter Rant.share_slug to be unique with default
        migrations.AlterField(
            model_name="rant",
            name="share_slug",
            field=models.SlugField(unique=True, max_length=12, default=rants.models.generate_share_slug),
        ),
        # Step 7: Alter SideBySide.share_slug to be unique with default
        migrations.AlterField(
            model_name="sidebyside",
            name="share_slug",
            field=models.SlugField(unique=True, max_length=12, default=rants.models.generate_share_slug),
        ),
    ]
