# Generated by Django 4.2.27 on 2025-12-12 22:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_text", models.TextField()),
                ("translated_text", models.TextField()),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("to_linkedin", "Make it LinkedIn"),
                            ("to_reality", "Make it Real"),
                        ],
                        max_length=20,
                    ),
                ),
                ("share_slug", models.SlugField(max_length=12, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("view_count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
